Check if timezone is empty

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -34,6 +34,14 @@ printf "Error empty admin password, installation aborted"
    exit 1
 fi
 
+# Check timezone
+if [[ -z "$timezone" ]]; then
+printf "Could not detect Timezone, please check /etc/timezone. Installation aborted"
+  exit 1
+else
+printf "Detected Timezone $timezone"
+fi
+
 # Check path not empty
 if [[ -z "$path" ]]; then
 printf "Error path is empty, installation aborted"
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -7,6 +7,14 @@ port=$(sudo yunohost app setting movim port)
 public_site=$(sudo yunohost app setting movim public_site)
 timezone=`cat /etc/timezone`
 
+# Check timezone
+if [[ -z "$timezone" ]]; then
+printf "Could not detect Timezone, please check /etc/timezone. Installation aborted"
+  exit 1
+else
+printf "Detected Timezone $timezone"
+fi
+
 # Install Movim files
 final_path=/var/www/movim
 sudo cp -a ../sources/* $final_path
